from pydantic import BaseModel
from pydantic import Field
from typing import Optional


class SQLQueryValidator(BaseModel):
    sql_query: str = Field(..., description="SQL query generated by the agent")
    sql_query_explanation: Optional[str] = Field(..., description="Explanation of the generated SQL query")

